name: Compile PS3EYEDriver for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download and Install MinGW64
      run: |
        curl -L -o mingw64.zip http://tdm-gcc.tdragon.net/download
        7z x mingw64.zip -oC:\mingw64
        echo "::add-path::C:\mingw64\bin"

    - name: Download and Install libusb-1.0
      run: |
        curl -L -o libusb-1.0.zip http://libusb.info/libusb-1.0.20.7z
        7z x libusb-1.0.zip
        mv libusb-1.0.20 libusb-1.0
        mv libusb-1.0 C:\PS3EYEDriver

    - name: Download and Install SDL2
      run: |
        curl -L -o SDL2.zip https://www.libsdl.org/release/SDL2-devel-2.0.4-mingw.tar.gz
        7z x SDL2.zip
        mv SDL2-2.0.4 SDL2
        mv SDL2 C:\PS3EYEDriver

    - name: Set up MinGW and SDL2 environment variables
      run: |
        setx PATH "C:\mingw64\bin;C:\PS3EYEDriver\SDL2\x86_64-w64-mingw32\bin;%PATH%"

    - name: Build PS3EYEDriver
      run: |
        cd C:\PS3EYEDriver
        mingw32-make

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ps3eyedriver
        path: C:\PS3EYEDriver\ps3eye_sdl.exe